In [5]:
import pickle
import pandas as pd
import torch
from dataloader import MELDDataset

import torch
from torch.utils.data import Dataset
from torch.nn.utils.rnn import pad_sequence
import pickle
import pandas as pd
import numpy as np
import os

import torch.nn as nn
from torch.utils.data import DataLoader
from torch.utils.data.sampler import SubsetRandomSampler
import torch.optim as optim

In [2]:
with open('trained_model.pkl', 'rb') as f:
    best_fscore, best_loss, best_label, best_pred, best_mask, best_attn = pickle.load(open('trained_model.pkl', 'rb'))

In [3]:
best_model = torch.load("new_model.pth")

In [17]:
data_path = 'DialogueRNN_features/MELD_features/'
batch_size = 30
n_classes = 7
n_epochs = 100
active_listener = False
attention = 'general'
class_weight = False
dropout = 0.1
rec_dropout = 0.1
l2 = 0.00001
lr = 0.0005
best_model = None

test_set = MELDDataset('DialogueRNN_features/MELD_features/MELD_features_raw_tri.pkl', 7, train=False)
test_loader = DataLoader(test_set,
                         batch_size=32, num_workers=0, pin_memory=False,
                         collate_fn=test_set.collate_fn)

In [178]:
d_id = 0
pred_out = []
total = 0
cur = 0
tmp = {0:-28, 1:8}
tmp2 = {2250:-2, 2294:-1, 2316:-1, 2338:-1, 2360:-1}
my_len = 0
for d in test_loader:
#     print(test_set[count][-2])
#     print(d[-2], len(d[-2]), len(d[-3]))
    count = 0
    print(d[-1])
    for d_id in d[-1]:
        if (d_id-1153) in test_set.videoIDs:
            print(test_set.videoIDs[d_id])
            my_len += len(test_set[d_id-1153][-2])
            print(best_label[total:total + len(test_set[d_id-1153][-2])])
            print(best_pred[total:total + len(test_set[d_id-1153][-2])])
            pred_out = np.append(pred_out, best_pred[total:total + len(test_set[d_id-1153][-2])])
            print(test_set[d_id-1153][-2])
            print(d[-2][count][:len(test_set[d_id-1153][-2])])
            print(best_label[total:total + len(d[-2][count])])
            assert((list(d[-2][count][:len(test_set[d_id-1153][-2])]) == best_label[total:total + len(test_set[d_id-1153][-2])]).all())
            print(len(d[-2][count]))
        
#         for utt_id in test_set.videoIDs[d_id]:
#             pred_unpadded += [elem[utt_id]]
        print(total, cur)
        if total >= 1560 and total < 1584:
            total += 4
        if total in tmp2:
            total += tmp2[total]
        if cur == 3:
            total -= 1
        if total >=2888 and total <3072:
            total += 1
        if total > 3071 and total < 3808:
            total += 2
        if total >= 4290 and total < 4506:
            total -= 5
        if total >= 4830 and total < 5028:
            total -= 3
        if total >= 5025 and total < 5280:
            total -= 7
        if total >= 5632 and total < 5940:
            total += 5
        total += len(d[-2][count])
        count += 1
    if cur in tmp:
        total += tmp[cur]
    cur += 1
print(count, my_len)

[1153, 1154, 1155, 1156, 1157, 1158, 1159, 1160, 1161, 1162, 1163, 1164, 1165, 1166, 1167, 1168, 1169, 1170, 1171, 1172, 1173, 1174, 1175, 1176, 1177, 1178, 1179, 1180, 1181, 1182, 1183, 1184]
[0, 1, 2]
[1 6 0]
[0 1 0]
tensor([1, 6, 0])
tensor([1, 6, 0])
[1 6 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
33
0 0
[0, 1, 2, 3, 4, 5, 6, 7]
[0 4 4 4 4 4 4 4]
[0 4 3 6 6 0 4 4]
tensor([0, 4, 4, 4, 4, 4, 4, 4])
tensor([0, 4, 4, 4, 4, 4, 4, 4])
[0 4 4 4 4 4 4 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
33
33 0
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[0 0 3 1 6 6 6 4 4 0 0]
[0 1 0 1 1 6 6 6 6 0 0]
tensor([0, 0, 3, 1, 6, 6, 6, 4, 4, 0, 0])
tensor([0, 0, 3, 1, 6, 6, 6, 4, 4, 0, 0])
[0 0 3 1 6 6 6 4 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
33
66 0
[0, 1, 2, 3, 4, 5, 6]
[0 2 0 0 6 5 0]
[0 1 0 1 0 1 0]
tensor([0, 2, 0, 0, 6, 5, 0])
tensor([0, 2, 0, 0, 6, 5, 0])
[0 2 0 0 6 5 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
33
99 0
[0, 1, 2, 3, 4, 5, 6, 7, 8]
[1 0 1

tensor([1, 0, 6, 6, 3])
[1 0 6 6 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
23
1951 2
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[3 0 0 0 0 0 0 4 4 4]
[1 0 0 0 0 0 0 0 4 4]
tensor([3, 0, 0, 0, 0, 0, 0, 4, 4, 4])
tensor([3, 0, 0, 0, 0, 0, 0, 4, 4, 4])
[3 0 0 0 0 0 0 4 4 4 0 0 0 0 0 0 0 0 0 0 0 0 0]
23
1974 2
[0, 1]
[0 0]
[0 0]
tensor([0, 0])
tensor([0, 0])
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
23
1997 2
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[6 6 5 6 6 0 0 6 0 0]
[6 6 6 6 6 6 6 6 0 0]
tensor([6, 6, 5, 6, 6, 0, 0, 6, 0, 0])
tensor([6, 6, 5, 6, 6, 0, 0, 6, 0, 0])
[6 6 5 6 6 0 0 6 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
23
2020 2
[0, 1]
[4 0]
[0 0]
tensor([4, 0])
tensor([4, 0])
[4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
23
2043 2
[0]
[0]
[0]
tensor([0])
tensor([0])
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
23
2066 2
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[0 0 0 0 4 6 1 3 0 3 6]
[3 3 0 0 1 6 1 3 0 3 6]
tensor([0, 0, 0, 0, 4, 6, 1, 3, 0, 3, 6])
tensor([0, 0, 0, 0, 4, 6, 1, 3, 0, 3, 6])
[0 0 0 0 4 6 1 3 0 3 

21
3784 4
[0, 1]
[6 6]
[3 3]
tensor([6, 6])
tensor([6, 6])
[6 6 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
21
3807 4
[1313, 1314, 1315, 1316, 1317, 1318, 1319, 1320, 1321, 1322, 1323, 1324, 1325, 1326, 1327, 1328, 1329, 1330, 1331, 1332, 1333, 1334, 1335, 1336, 1337, 1338, 1339, 1340, 1341, 1342, 1343, 1344]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
[3 6 6 6 6 6 3 3 6 6 3 3 3 6]
[6 6 6 0 6 6 6 6 6 6 6 6 6 6]
tensor([3, 6, 6, 6, 6, 6, 3, 3, 6, 6, 3, 3, 3, 6])
tensor([3, 6, 6, 6, 6, 6, 3, 3, 6, 6, 3, 3, 3, 6])
[3 6 6 6 6 6 3 3 6 6 3 3 3 6 0 0 0 0 0 0 0 0 0]
23
3830 5
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
[0 0 0 4 4 0 4 0 0 0 4 1]
[0 0 0 6 4 4 4 0 0 0 0 1]
tensor([0, 0, 0, 4, 4, 0, 4, 0, 0, 0, 4, 1])
tensor([0, 0, 0, 4, 4, 0, 4, 0, 0, 0, 4, 1])
[0 0 0 4 4 0 4 0 0 0 4 1 0 0 0 0 0 0 0 0 0 0 0]
23
3853 5
[0, 1, 2, 3, 4, 5]
[4 0 0 0 0 6]
[6 0 0 0 0 0]
tensor([4, 0, 0, 0, 0, 6])
tensor([4, 0, 0, 0, 0, 6])
[4 0 0 0 0 6 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
23
3876 5
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9

22
5190 7
[0]
[0]
[0]
tensor([0])
tensor([0])
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 4 0 0 0 0 0 0]
22
5205 7
[0]
[4]
[4]
tensor([4])
tensor([4])
[4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 5 1 5 6]
22
5220 7
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
[0 0 0 5 1 5 6 4 6 3 4 0]
[0 0 0 0 1 0 0 6 3 6 0 0]
tensor([0, 0, 0, 5, 1, 5, 6, 4, 6, 3, 4, 0])
tensor([0, 0, 0, 5, 1, 5, 6, 4, 6, 3, 4, 0])
[0 0 0 5 1 5 6 4 6 3 4 0 0 0 0 0 3 0 0 0 0 0]
22
5235 7
[0, 1, 2, 3, 4]
[0 3 0 0 0]
[0 6 0 0 6]
tensor([0, 3, 0, 0, 0])
tensor([0, 3, 0, 0, 0])
[0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 6 1 0 0 0 0]
22
5250 7
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
[0 6 1 0 0 0 0 0 0 0 0 0]
[0 3 1 3 0 0 0 0 0 0 0 0]
tensor([0, 6, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([0, 6, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])
[0 6 1 0 0 0 0 0 0 0 0 0 0 0 0 6 6 6 3 1 0 3]
22
5265 7
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
[6 6 6 3 1 0 3 4 0 4 1 0 1 0 1 3 1]
[6 1 1 1 1 1 1 0 1 3 1 0 3 0 0 0 0]
tensor([6, 6, 6, 3, 1, 0, 3, 4, 0, 4, 1, 0, 1, 0, 1, 3, 1

In [61]:
best_label[31*33:32*33]

array([0, 0, 0, 0, 0, 1, 4, 0, 0, 0, 3, 0, 0, 1, 3, 3, 3, 4, 0, 0, 0, 0,
       0, 0, 3, 6, 0, 0, 1, 3, 3, 0, 0])

In [32]:
print(np.count_nonzero(best_label==best_pred))

3645


In [33]:
len(best_label)

6110

In [44]:
test_set.videoIDs

{0: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
 1: [0, 1, 2, 3, 4, 5, 8],
 2: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
 3: [0, 1, 2, 3, 4, 5, 6, 8, 9],
 4: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14],
 5: [0, 1, 2, 3],
 6: [0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21],
 7: [0, 1],
 8: [0, 1, 2, 3, 4, 5, 6],
 9: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
 10: [0, 1, 2, 3, 4, 5],
 11: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 12: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
 13: [0, 1, 2, 3],
 14: [0, 1, 2, 3, 4, 5],
 15: [0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22],
 16: [0, 1, 2, 3, 4, 5],
 17: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
 18: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
 19: [0, 1],
 20: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
 21: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
 22: [0, 1, 2, 3],
 23: [0,

In [48]:
60 in test_set.videoIDs

False

In [148]:
df = pd.read_csv("test_sent_emo.csv")

In [151]:
df['Dialogue_ID'].unique()

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [165]:
try_count = 0
for i, row in df.iterrows():
    if row['Dialogue_ID'] not in test_set.videoIDs:
        print(row)
print(try_count)

Sr No.                                                        584
Utterance       Yeah, but what if it's not? What if there    i...
Speaker                                                  Chandler
Emotion                                                      fear
Sentiment                                                negative
Dialogue_ID                                                    60
Utterance_ID                                                    0
Season                                                          9
Episode                                                        21
StartTime                                            00:18:12,091
EndTime                                              00:18:16,928
Name: 537, dtype: object
Sr No.                                                        585
Utterance       Oh, Chandler, look. You and Monica are meant t...
Speaker                                                    Janice
Emotion                                            

In [168]:
new_df = df[df['Dialogue_ID']!= 60]

In [179]:
len(pred_out)

2603

In [182]:
dict_emo = {0: 'neutral', 1: 'surprise', 2:'fear', 3:'sadness', 4:'joy', 5:'disgust', 6:'anger'}

In [186]:
import copy
new_df = copy.deepcopy(new_df)

In [187]:
new_df["Pred_Emotion"] = [dict_emo[l] for l in pred_out]

In [188]:
new_df

Sr No.                                          Utterance Speaker  \
0          1  Why do all you’re coffee mugs have numbers on ...    Mark   
1          2  Oh. That’s so Monica can keep track. That way ...  Rachel   
2          3                                       Y'know what?  Rachel   
3         19                     Come on, Lydia, you can do it.    Joey   
4         20                                              Push!    Joey   
...      ...                                                ...     ...   
2605    2760  Yeah, I mean, come on Ross, no one will even n...  Rachel   
2606    2761                      They’re not listening too me?    Ross   
2607    2762  Of course they’re listening to you! Everybody ...  Rachel   
2608    2763  Monica you really think I should try this phas...    Ross   
2609    2764                             I think you look fine.  Monica   

       Emotion Sentiment  Dialogue_ID  Utterance_ID  Season  Episode  \
0     surprise  positive            0             0       3       19   
1        anger  negative            0             1       3       19   
2      neutral   neutral            0             2       3       19   
3      neutral   neutral            1             0       1       23   
4          joy  positive            1             1       1       23   
...        ...       ...          ...           ...     ...      ...   
2605   neutral   neutral          279            11       6        4   
2606  surprise  negative          279            12       6        4   
2607   neutral   neutral          279            13       6        4   
2608   neutral   neutral          279            14       6        4   
2609   neutral   neutral          279            15       6        4   

         StartTime       EndTime Pred_Emotion  
0     00:14:38,127  00:14:40,378      neutral  
1     00:14:40,629  00:14:47,385     surprise  
2     00:14:56,353  00:14:57,520      neutral  
3      0:10:44,769   0:10:46,146      neutral  
4      0:10:46,146   0:10:46,833          joy  
...            ...           ...          ...  
2605  00:14:35,457  00:14:40,211        anger  
2606  00:14:42,256  00:14:43,840        anger  
2607  00:14:44,008  00:14:48,511        anger  
2608  00:14:48,138  00:14:52,390      sadness  
2609  00:14:52,558  00:14:54,183      neutral  

[2603 rows x 12 columns]

In [190]:
print((new_df["Pred_Emotion"] == new_df["Emotion"]).value_counts())

True     1510
False    1093
dtype: int64


In [191]:
new_df.to_csv('prediction_emotion_output.csv')